title:            Adam King
tagline:          Energy Trader
description:      Personal site for Adam King, focussed on energy trading and software development.
canonical:        http://adamking.eu

# Owner/author information
owner:
  name:           Adam King
  email:          contact@adamking.energy
  github:         adamkingenergy
  linkedin:       adamkinguk
  location:       "London"

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Links to include in top navigation
# For external links add external: true
links:
  - title: About
    url: /about

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
